#!/usr/bin/with-contenv bash

if [ ! -d /cache ]; then
    echo "WARN: Please modify your cache volume mount from '/tmp' to '/cache'"
    sleep infinity
fi

# make folders
mkdir -p \
    /config/log

touch /config/rclone.conf

# permissions
chown -R abc:abc \
    /config \
    /cache
