#!/usr/bin/with-contenv bash

export HOME=/config

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z 127.0.0.1 51515" \
        s6-setuidgid abc \
            kopia server start \
                --insecure \
                --disable-csrf-token-checks \
                --address=0.0.0.0:51515 \
                --server-username=${USERNAME:-kopia} \
                --server-password=${PASSWORD:-kopia}
