---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - docker-bake.hcl
      - "root/**"
      - "tests/**"
      - ".github/**"
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        default: true

permissions:
  contents: read

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Image
    uses: ./.github/workflows/build.yaml
    permissions:
      artifact-metadata: write
      attestations: write
      contents: write
      id-token: write
      packages: write
      security-events: write
    with:
      release: ${{ github.event_name == 'workflow_dispatch' && inputs.release || github.event_name == 'push' }}

  status:
    if: ${{ !cancelled() }}
    name: Release Success
    needs: build
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
      - if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: echo "Release passed"
